# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fa55a28191dd6d7a9f8512375b8ff951d22f92144680591e87d42e7aa25ce1beef847255e355cc3f581c24a0a22eb244614a926b56f3fcae2d567a80e0c1ec8

test:
  secret_key_base: 368ae1a05b45044e94f47561e05f20b792630137ca950a528b04eb9d525e04b4a188abfe3d29040acd67f283eaa2f6859586aef0a9203fce03929608f8e44488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
